Repository scikit-hep/vector, pull requests merged in 2023-02, with the labels that each got.

#231 feat: add constructors for `VectorObject3D` and `MomentumObject3D`
  docs/changelog.md
  src/vector/_methods.py
  src/vector/backends/object.py
  tests/backends/test_object.py
  tests/compute/lorentz/test_boost_beta3.py
  tests/compute/spatial/test_costheta.py
  tests/compute/spatial/test_cottheta.py
  tests/compute/spatial/test_cross.py
  tests/compute/spatial/test_deltaR.py
  tests/compute/spatial/test_deltaR2.py
  tests/compute/spatial/test_deltaangle.py
  tests/compute/spatial/test_deltaeta.py
  tests/compute/spatial/test_eta.py
  tests/compute/spatial/test_mag.py
  tests/compute/spatial/test_mag2.py
  tests/compute/spatial/test_rotateX.py
  tests/compute/spatial/test_rotateY.py
  tests/compute/spatial/test_rotate_axis.py
  tests/compute/spatial/test_rotate_euler.py
  tests/compute/spatial/test_rotate_quaternion.py
  tests/compute/spatial/test_theta.py
  tests/compute/spatial/test_z.py
  tests/compute/test_add.py
  tests/compute/test_dot.py
  tests/compute/test_equal.py
  tests/compute/test_isclose.py
  tests/compute/test_not_equal.py
  tests/compute/test_scale.py
  tests/compute/test_subtract.py
  tests/compute/test_unit.py
Labels: feature

#232 feat: add constructors for `VectorObject4D` and `MomentumObject4D`
  src/vector/_methods.py
  src/vector/backends/numpy.py
  src/vector/backends/object.py
  tests/compute/lorentz/test_beta.py
  tests/compute/lorentz/test_boostX_beta.py
  tests/compute/lorentz/test_boostX_gamma.py
  tests/compute/lorentz/test_boostY_beta.py
  tests/compute/lorentz/test_boostY_gamma.py
  tests/compute/lorentz/test_boostZ_beta.py
  tests/compute/lorentz/test_boostZ_gamma.py
  tests/compute/lorentz/test_boost_beta3.py
  tests/compute/lorentz/test_boost_p4.py
  tests/compute/lorentz/test_rapidity.py
  tests/compute/lorentz/test_t.py
  tests/compute/lorentz/test_t2.py
  tests/compute/lorentz/test_tau.py
  tests/compute/lorentz/test_tau2.py
  tests/compute/lorentz/test_to_beta3.py
  tests/compute/spatial/test_cross.py
  tests/compute/spatial/test_deltaR.py
  tests/compute/spatial/test_deltaR2.py
  tests/compute/spatial/test_deltaangle.py
  tests/compute/spatial/test_deltaeta.py
  tests/compute/spatial/test_rotateX.py
  tests/compute/spatial/test_rotateY.py
  tests/compute/spatial/test_rotate_axis.py
  tests/compute/test_add.py
  tests/compute/test_dot.py
  tests/compute/test_equal.py
  tests/compute/test_isclose.py
  tests/compute/test_not_equal.py
  tests/compute/test_scale.py
  tests/compute/test_subtract.py
  tests/compute/test_unit.py
Labels: feature

#316 fix: better elif conditions for obj __init__ methods
  src/vector/backends/object.py
Labels: bug

#278 feat: update `to_Vector3D` to pass new coordinate values
  src/vector/_methods.py
Labels: feature

#320 docs: a readable changelog
  docs/changelog.md
Labels: docs

#319 feat: allow passing coordinates to to_Vector*D
  src/vector/_methods.py
  src/vector/backends/object.py
  tests/backends/test_awkward.py
  tests/backends/test_numpy.py
  tests/backends/test_object.py
Labels: feature
